version: '2'

services:
  sut:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /bin/sh -c 'sleep 5; /env/bin/nosetests -v /app/service/test/integration/tests.py'
    links:
      - web
    depends_on:
      - migrate
    environment:
      SERVER_URL: http://web:5000
      SECRET_KEY: asdklfjeoja039rjdlkjfaoi3rdk
      DATABASE_URL: postgres://username:password@database/test
      
  upgrade:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /bin/sh -c 'sleep 5; /env/bin/nosetests -v /app/service/test/integration/tests.py'
    links:
      - web
    depends_on:
      - web
    environment:
      SERVER_URL: http://web:5000
      SECRET_KEY: asdklfjeoja039rjdlkjfaoi3rdk
      DATABASE_URL: postgres://username:password@database/test
      
  migrate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /bin/sh -c 'sleep 5; /env/bin/nosetests -v /app/service/test/integration/tests.py'
    links:
      - web
    depends_on:
      - upgrade
    environment:
      SERVER_URL: http://web:5000
      SECRET_KEY: asdklfjeoja039rjdlkjfaoi3rdk
      DATABASE_URL: postgres://username:password@database/test

